### ISSUE TITLE
Spotify Premium needed

### ISSUE THREAD

**Issue by MiauMiez** [justin025/onthespot#1]
Hey there, 

first of all, I want to thank you for working on this project. But I am having a problem with it. When I have to select the device in the Spotify desktop-app, it tells me that I need a premium subscription. 

Is there anything I can do?

**Comment by justin025** [comment]
I've tested 2 free accounts with this feature and they both worked fine, maybe it differs depending on your country?

You have two options, 
A. I could send you one of my test accounts lol
B. Use a premium free trial

We could in theory build auth using developer tokens but once again every free account I've tried worked fine so I don't really intend to develop this feature unless there is demand.

**Comment by montimatte** [comment]
I got the same problem in Italy. 
Is there any way to bypass this?
I don't how the credentials file is, but if it's in plain you could share it and we could edit it with our login details.

**Comment by justin025** [comment]
Could you guys try the file below and let me know if it works:
https://gofile.io/d/7dK593

**Comment by justin025** [comment]
Fixed login bug for free accounts and other minor things in 0.6.1 https://github.com/justin025/onthespot/releases/tag/v0.6.1

If you have any further issues feel free to reopen
