### ISSUE TITLE
Not downloading updated spotify playlists

### ISSUE THREAD

**Issue by Rubsnub** [justin025/onthespot#11]
Hi! First of all, thank you a lot for the work on this version of OntheSpot! 

The problem is this: When you have downloaded a spotify playlist through the app, there is no problem. But when you add songs to that playlist and you want to download it again through the app to add these new songs, it doesn't seem to find these new songs. With the old version of OntheSpot you could delete the cache and it would find the updated playlist again. I was just wondering where I can find the cache for the app if there is any? It is not in the same place where the cache of the original app used to be.

Thank you in advance, and thank you again for making this version!

**Comment by justin025** [comment]
In an effort to reduce calls to the spotify api the original onthespot dev cached responses, which makes sense for tracks and albums that do not change but playlists should probably not be cached, I will add this to the dev build somepoint this week.

As a temporary solution you can delete your request cache at %localappdata%/Temp/onthespot/reqcache or create a new playlist and copy the songs over

**Comment by Rubsnub** [comment]
Thanks for you quick response! I found the temp folder but there was no
onthespot to be found. I just deleted all the contents of the temp appdata
folder and that seemed worked though. But I'm definitely looking forward
to your update, that should make things a lot easier!

**Comment by Rubsnub** [comment]
Thanks for you quick response! I found the temp folder but there was no onthespot to be found. I just deleted all the contents of the temp appdata folder and that worked though. But I'm definitely looking forward to your update, that should make things a lot easier!

**Comment by justin025** [comment]
Fixed in the latest dev build here:
https://github.com/justin025/onthespot/releases/dev

**Comment by Rubsnub** [comment]
It seems to works like a charm, thanks for the quick update!
