### ISSUE TITLE
FEATURE REQUEST: Reason behind .ogg not being bale to embed cover art, etc

### ISSUE THREAD

**Issue by Tribalwarfare** [justin025/onthespot#12]
Hi,

Thank you for your fork, it works great for my academic testing purposes. especially the convenient app Image build.

I have two queries:

May I kindly enquire as to why the .ogg raw dumps cannot have the cover art etc embedded via ffmpeg as with the .mp3 versions? Is it possible to do so?

Is it also possible to enable file version detection patterns for .mp3 and .ogg?
For example I have existing test files with .ogg extension but the file name has the same naming convention:
{artist}/{album}/{track_number}. {name}

So say the destination directory has a an existing file named **1_trackname.ogg**
I enable .mp3 save formatting and I do not want onthespot to save a version name **1_trackname.mp3** if the .ogg version already exists with the same name/pattern. The same in reverse for .ogg RAW saves when the .mp3 version exists with the same name.

Is it possible to update it to have an toggle to ignore the file name extension and just focus on the name of the file itself when checking for existing version?

This will greatly assist with mixed libraries and avoid dumps of titles which might already exist with a different container format.

Thanks for the great work :)

**Comment by justin025** [comment]
Both of your features are included in the latest dev appimage [here](https://github.com/justin025/onthespot/releases/dev), thanks for the suggestions

**Comment by Tribalwarfare** [comment]
> Both of your features are included in the latest dev appimage [here](https://github.com/justin025/onthespot/releases/dev), thanks for the suggestions

WOW! Awesome and thank you for reviewing my request and feedback. I will grab the latest version now and start testing :)
