### ISSUE TITLE
MacOS Installation Issues

### ISSUE THREAD

**Issue by thethirteenthgay** [justin025/onthespot#18]
Since the page [here](https://github.com/justin025/onthespot/blob/main/docs/installation.md)'s most recent update, I seem to be unable to install on MacOs following these instructions. The .dmg file [here](https://github.com/justin025/onthespot/releases) already doesn't work for me (when opening via Finder, it just bounces once and does nothing. Opening through Applications normally gives a security error), but I was previously able to install fine through the instructions. 

However, now the only installation option (after downloading the source code, which works fine!) is 'Run [build_mac.sh](https://github.com/justin025/onthespot/blob/main/docs/scripts/build_mac.sh) in Terminal with ./scripts/build_mac.sh.', and Terminal just keeps telling me 'no such file or directory: /scripts/build_mac.sh'. 

Is this an issue with my laptop or with my inexpertise at coding, or is anyone else enountering this? And whichever, does anyone know how to bypass it?

Mac: Big Sur 11.7.10 

Thanks!

**Comment by justin025** [comment]
I might have already asked this but is this an intel or m1/m2 mac and what security error do you see, post a screenshot here. I am not sure why the dmg builds do not run on your laptop as other users have ran them fine, feel free to dm me on discord and I could trouble shoot a bit more for you, @j075046.

As for building the application you need to run the following first to download the required files
```bash
git clone https://github.com/justin025/onthespot
cd onthespot
./scripts/build_mac.sh
```

Thanks for pointing out that the build instructions need to be a bit more precise for non-advanced users, I will fix them now

**Comment by thethirteenthgay** [comment]
It's an Intel! I don't actually get an error when opening through Finder (right click->open->open anyway). The app just bounces once and refuses to open without telling me why. When attempting to open normally on first download, I get the standard Mac security error (screenshot attached). 
And I did run the above script (apologies if I didn't make that clear in my original post!). Re-running it tells me: 'fatal: destination path 'onthespot' already exists and is not an empty directory.
zsh: no such file or directory: ./scripts/build_mac.sh.' 


The error is with the 'no such file or directory' coming up even after running the original script! 

<img width="373" alt="Screenshot 2024-10-07 at 12 11 56" src="https://github.com/user-attachments/assets/be165939-7418-46d5-9dba-97888c9a44bb">

**Comment by thethirteenthgay** [comment]
@justin025 hi, sorry to bother you again but I'm just wondering if there's any update on this! alternatively I did send you a friend request on Discord - I can't send you a DM until it's accepted, seemingly - so if you'd prefer to troubleshoot this there I'm happy to! thank you :)

**Comment by eolverag** [comment]
What worked for me was that after opening the DMG file and moving the APP to the APP folder, you need to go to settings then privacy and security then scroll down until you the app asking for permission to open should be under security section. just gran the app permission to open. thats it , that worked for me.

**Comment by justin025** [comment]
@thethirteenthgay I think I added you back

**Comment by twain-28** [comment]
Can confirm the exact same issue on MacOS Monterey 12.7.6, both with the 0.7ish and compiled source.
I even added the compiled app to the exclusions from Gatekeeper, by using Gatekeeper Helper, but it just crashes at boot, right after making a single "bounce" on macOS bar.
Any help or tracing of the error I could provide you with, just ask...in the meantime, I'll lurk here...

**Comment by twain-28** [comment]
EDIT: _I correct myself_
I can confirm compiling actual branch (1.0ish, most recent) **TOTALLY works on Mac**, albeit with a few corrections to the installation procedure:
1. build_mac.sh **needs to be moved to main folder and ran there**, however...
2. "wget ffmpeg" does not seem to work properly, and no ffmpeg, no joy. This, however, can be easily bypassed by _manually downloading ffmpeg-7.1.zip_ (at https://evermeet.cx/ffmpeg/ffmpeg-7.1.zip, see buld_mac.sh, line 22), then creating a folder named "build" in the main one (so "onthespot/build"), placing the file there and renaming it as "ffmpeg.zip".
3. after doing everything described above, you just comment away the lines in "build_mac.sh" where the "build" folder is created and ffmpeg downloaded (21-22), save the file and run it.

**Comment by trulow** [comment]
> EDIT: _I correct myself_ I can confirm compiling actual branch (1.0ish, most recent) **TOTALLY works on Mac**, albeit with a few corrections to the installation procedure:
> 
>     1. build_mac.sh **needs to be moved to main folder and ran there**, however...
> 
>     2. "wget ffmpeg" does not seem to work properly, and no ffmpeg, no joy. This, however, can be easily bypassed by _manually downloading ffmpeg-7.1.zip_ (at https://evermeet.cx/ffmpeg/ffmpeg-7.1.zip, see buld_mac.sh, line 22), then creating a folder named "build" in the main one (so "onthespot/build"), placing the file there and renaming it as "ffmpeg.zip".
> 
>     3. after doing everything described above, you just comment away the lines in "build_mac.sh" where the "build" folder is created and ffmpeg downloaded (21-22), save the file and run it.

Thanks for this, worked on building 1.0.1 for my intel based mac. However, it seems like it doesn't work for version 1.0.2
Do you happen to know how to build 1.0.2 properly?

**Comment by twain-28** [comment]
> Thanks for this, worked on building 1.0.1 for my intel based mac. However, it seems like it doesn't work for version 1.0.2 Do you happen to know how to build 1.0.2 properly?

Yes I do: same thing worked fine for me, **just as long as you use the source specifically provided for 1.0.2**, not the git clone one (I guess something more _did_ break along the way...).
[I have other issues on 1.0.2](https://github.com/justin025/onthespot/issues/62), but I would say sticking with 1.0.1 still works quite well, IMHO.

**Comment by trulow** [comment]
Looks like 1.0.3 has issues when building from source as well.

While the script (build_mac.sh) no longer needs the lines where the build folder is created and ffmpeg is downloaded/extracted (21-23). The file still needs to be moved to the root dir.

However, the resulting app still does not work on Intel based macs (I don't have an M series chip to test).

**Comment by justin025** [comment]
@trulow The app will build on intel macs if you run the script on an intel mac, can you provide the full output of your build so I can look for any errors

**Comment by justin025** [comment]
The app seems to build fine for ventura and bigsur using the instructions below. As the issues listed don't seem to occur any longer I'll mark this issue as closed.

1. Download and extract the source code (or git clone)
2. Open a terminal window and type 'cd '
3. Now drag the source code folder into the terminal window and hit enter
4. run ./scripts/build_mac.sh

*You may need to have xcode developer tools installed, the install prompt will appear if you open the terminal window and type 'git'*
