### ISSUE TITLE
Metadata download issue with specific tracks

### ISSUE THREAD

**Issue by grochamou** [justin025/onthespot#19]
### Bug Description

The metadata failed to download for the following tracks:

https://open.spotify.com/track/1WrUvMlHafQCexT8bESbKF
https://open.spotify.com/track/3i7CcXJ7xQtIZpkspBPOb4

When downloading the albums, these tracks failed to download metadata but they show up in the downloads tab.
When entering the URL in the search field, the tracks don't show up in the downloads tab.

### Environment Details

```markdown
| **Detail**               | **Your Information**                 |
|--------------------------|--------------------------------------|
| **Operating System**     | MacOS 15.0.1                         |
| **Application Version**  | v0.7.1                               |
| **Installation Method**  | Build from Script                    |
| **Python Version**       | 3.12.7                               |
| **FFmpeg Version**       | 7.1                                  |
```

**Comment by justin025** [comment]
Issue fixed in latest commit, let me know if it still occurs
