### ISSUE TITLE
Unable to login using Spotify session 

### ISSUE THREAD

**Issue by GeorgeHicham** [justin025/onthespot#2]
I have a Spotify premium account and this is the 1st time for me to login to OnTheSpot. 
I installed the 0.6 release as I could not login on the 0.5 release. 
I could not login on version 0.6 either. 
Here's the steps followed: 

1. I launched OnTheSpot on Windows. 
2. Message "No session available for , login to at least one account !" has been shown
3. Message dismissed by clicking "Ok"
4. Browser to "Configurations"
5. Clicked on "Add account"
6. Message "Login Service Started... Select ''OnTheSpot" under devices in the Spotify Desktop App." has been shown
7. Launched Spotify Windows App
8. Played a song
9. Clicked on "Connect to a device"
10. I can see the device "OnTheSpot" listed. 
11. Selected the device 
12. I can see the message "Connecting to OnTheSpot" shown
13. Nothing happens.. 

Here's the log for this session for your reference: [onthespot.log](https://github.com/user-attachments/files/16828765/onthespot.log)

PS: I can see the file "credentials.json" created in the root folder of the OnTheSpot application. Attempted to terminate and relaunch the application but the same scenario took place.

**Comment by justin025** [comment]
Could you try the following file, if it doesnt work I listed the manual method below (though i think the new exe should work)
https://gofile.io/d/7dK593

If you see the credentials.json then the login method should have worked. Not sure what the issue was exactly, logs don't show anything. Rename credentials.json to 'ots_login_a.json'. Move it to .config/onthespot/sessions and finally edit config.json so that the accounts section looks like this:
    "accounts": [
        [
            "USERNAME",
            "true",
            1,
            "a"
        ]
    ],

**Comment by justin025** [comment]
Can you try this update and let me know if it works
 https://gofile.io/d/7dK593

**Comment by justin025** [comment]
I fixed the login bug in v0.6 here, if you have any further issues feel free to reopen the issue 
https://github.com/justin025/onthespot/releases/tag/v0.6.1

**Comment by GeorgeHicham** [comment]
> I fixed the login bug in v0.6 here, if you have any further issues feel free to reopen the issue https://github.com/justin025/onthespot/releases/tag/v0.6.1

Works like a charm!
It also solved the issue where a free account could not select OnTheSpot as a casting device.

Thanks for the prompt response & resolution.
