### ISSUE TITLE
Freeze Issue when donwloading from Artist

### ISSUE THREAD

**Issue by julerobb1** [justin025/onthespot#21]
### Bug Description

When trying to download the A*Teens from the artist page, using the open.spotify.com link the app freezes
![image](https://github.com/user-attachments/assets/d0005649-a3de-447f-b5c1-6827bfb68e85)

### Environment Details

```markdown
| **Detail**               | **Your Information**                 |
|--------------------------|--------------------------------------|
| **Operating System**     | Windows 11 Professional Workstation  |
| **Application Version**  | v0.7.0                               |
| **Installation Method**  | GitHub Release / Build from Script   |
| **Python Version**       | 3.11.4                               |
| **FFmpeg Version**       | e.g., 4.3.1                          |
```

**Comment by V1p3rOne** [comment]
Hello @julerobb1 Could you please fill out the **Environment Details** including the Versions that you use? Also is this the first time it happened?

**Comment by julerobb1** [comment]
i believe I figured it out for some unknown reason the force premium checkbox was checked. unchecking fixed the issue.

**Comment by V1p3rOne** [comment]
Yeah sure. If you encounter any other issues or still have the same issue just msg in Discord or open up another Issue here
