### ISSUE TITLE
OGG and MP3 Format Lyrics, Cover Art Continued

### ISSUE THREAD

**Issue by Tribalwarfare** [justin025/onthespot#23]
### Bug Description

Hi, Sorry for the wait but I have completed a fresh new round of testing with v0.7.1 app image.

A couple of things:

1. .OGG Cover art and Lyric embeds still do not work.
![image](https://github.com/user-attachments/assets/46072e1a-61bc-49f5-8ad7-7db794db76b5)

2. .MP3 format embeds cover art, can download lyrics file but does not embed lyrics inside .mp3 file:

![image](https://github.com/user-attachments/assets/77d0b8cf-5436-4077-936a-8b41ae7ee736)

I have attached the settings.json file and one mp3 session log and one session log for one mp3 and .ogg attempt on the same song:
[config.json](https://github.com/user-attachments/files/17362054/config.json)
[onthespot_mp3_sessions.log](https://github.com/user-attachments/files/17362056/onthespot_mp3_sessions.log)
[onthespot_ogg.log](https://github.com/user-attachments/files/17362979/onthespot_ogg.log)

Raw Console launch output .txt dump:
[raw_console.txt](https://github.com/user-attachments/files/17363009/raw_console.txt)

Here is a screenshot from an .ogg file with lyrics and cover embedded taken with Spytify, maybe it helps figure the storage out:

![image](https://github.com/user-attachments/assets/b61fab0e-8c9f-4bad-bf13-a7fc7efe9ed7)
![image](https://github.com/user-attachments/assets/3f87384f-7730-4d2e-a5ae-341cf2bc64d8)

I hope this helps narrow down the issue.

### Environment Details

```markdown
| **Detail**               | **Your Information**                 |
|--------------------------|--------------------------------------|
| **Operating System**     | Debian 12,Testing, KDE               |
| **Application Version**  | v0.7.1                               |
| **Installation Method**  | AppImage Release v0.7.1              |
```

**Comment by justin025** [comment]
closing this in favor of https://github.com/justin025/onthespot/issues/13
