### ISSUE TITLE
Application Not Responding when search with URL (Artist, Playlist. etc) that have so many song.

### ISSUE THREAD

**Issue by nooobmster69** [justin025/onthespot#27]
### Bug Description

I have experience an Error when i try to Search with url of artist sometime playlist with alot of song and some already existing in folder.

I think this should be normal for check existing file i folder, 
but i recommend to make each checking process in a thread to prevent Freezing.

Thanks Justin. You Did such a great Job.

![image](https://github.com/user-attachments/assets/1e9f3eaf-a02a-4dbd-b97f-847bf65b9502)

### Environment Details

```markdown
| **Detail**               | **Your Information**                 |
|--------------------------|--------------------------------------|
| **Operating System**     | Windows 10 / MacOS 13 / Ubuntu 22.04 |
| **Application Version**  | v0.7.0                               |
| **Installation Method**  | GitHub Release / Build from Script   |
| **Python Version**       | 3.11.4                               |
| **FFmpeg Version**       | e.g., 4.3.1                          |
```

**Comment by justin025** [comment]
currently rewriting the application and I have this issue fixed in an upcoming release. I'll keep you posted

**Comment by nooobmster69** [comment]
Thanks you so much.

**Comment by justin025** [comment]
Could you try this release and let me know how it goes
https://github.com/justin025/onthespot/releases/tag/v1.0.0

**Comment by justin025** [comment]
Feel free to reopen the issue or dm me if the problem persists.
