### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Aether0Pneuma** [justin025/onthespot#28]
### Bug Description

When i try to add account, i get an error:

Traceback (most recent call last):
  File "portable.py", line 5, in <module>
  File "__init__.py", line 62, in main
  File "gui\mainui.py", line 204, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Temp\\_MEI288722\\onthespot\\resources\\themes\\dark.qss'

### Environment Details

```markdown
| **Detail**               | **Your Information**                 |
|--------------------------|--------------------------------------|
| **Operating System**     | Windows 10 / MacOS 13 / Ubuntu 22.04 |
| **Application Version**  | v0.7.0                               |
| **Installation Method**  | GitHub Release / Build from Script   |
| **Python Version**       | 3.11.4                               |
| **FFmpeg Version**       | e.g., 4.3.1                          |
```

**Comment by justin025** [comment]
update to v0.7.2 and try again

**Comment by Aether0Pneuma** [comment]
> update to v0.7.2 and try again

It's already 0.7.2.

0.7.1 returns these errors and nothing works:
![изображение_2024-10-18_093259292](https://github.com/user-attachments/assets/e004c9d9-d9df-4d1a-820e-b39d5f6960cf)
![изображение_2024-10-18_093308942](https://github.com/user-attachments/assets/fcc82f6d-02be-4986-a299-19fbd2d72d56)

**Comment by justin025** [comment]
Could you try this release:
https://github.com/justin025/onthespot/releases/tag/v1.0.0

 if the issue persists then please send me logs at %localappdata%/Temp/onthespot

**Comment by justin025** [comment]
Should be fixed in newer releases feel free to reopen the issue if not.
