### ISSUE TITLE
About  FLAC (Free lossless Audio Code), Does it True uncompressed or Upscale from .Ogg?

### ISSUE THREAD

**Issue by nooobmster69** [justin025/onthespot#29]
### Feature Description

Hey Justin.
May i ask about **FLAC file.**
I have download many song with this file and its sound so good in High and Low Frequency details and crystal clear . but i wonder does that file was upscale from ***.ogg** or it True Lossless Audio file.

Thanks you.

### Justification

If it True Lossless Audio File it so good.
Like a screen shot in this attachment.
both was download with **Spotify Premium** and the result of **FLAC and M4A 320kbp**s noticeably different base on Audio Spectrum.

### Additional Information

![image_2024-10-15_21-39-36](https://github.com/user-attachments/assets/e1fbffc7-cee9-41e4-844f-4f092c1fc308)

**Comment by justin025** [comment]
You clearly have more knowledge than me regarding audio formats, do you have discord or some other place we can talk?

**Comment by nooobmster69** [comment]
yes have i'll reach out to you.

**Comment by justin025** [comment]
Sounds good, j075046

**Comment by oskarparsim** [comment]
Hey, I can also provide some input on this if necessary. Please update me with the answer :)

**Comment by justin025** [comment]
Sorry for missing this, spotify provides 320kbps ogg files (on a premium account) so upscaling to flac would have have the same quality in a different file format.
