### ISSUE TITLE
Some songs and albums fail to download no matter the length of wait-time, but they download using old OnTheSpot

### ISSUE THREAD

**Issue by 0rkaM** [justin025/onthespot#31]
### Bug Description

Downloading Devo album always fails, no matter if trying entire album, or single song, no matter if waiting any amount of time. This is the link of the album in question: https://open.spotify.com/album/1u2Qni8cVRptDTaA00fmBC?si=L_RBYssDRTGjEFX6cB_8rg

I use this tool, because I can get all the ID3 tags filled in automatically, which is a huge plus for me compared to before, when I used the other OnTheSpot from Casualsnek (https://github.com/casualsnek/onthespot)

But since this version of OnTheSpot failed so many time to get this album, I thought I would tried the old version and this time it did download without hiccups... to bad that it used the old authenticator, so after using it few time for other download that failed with this tool, my account was disconnected and I had to reset password, so since Casualsnek's OnTheSpot cannot be authenticated and be used anymore.
  

### Environment Details

```markdown
| **Detail**               | **Your Information**   |
|--------------------------|------------------------|
| **Operating System**     | Windows 10             |
| **Application Version**  | v0.7.0                 |
| **Installation Method**  | GitHub Release v0.7.1  |
| **Python Version**       | 3.10.8                 |
| **FFmpeg Version**       | various versions local to program: 
                             Audacity, Losslesscut, 
                             TAudio Converter, FL Studio,
                             Roland Cloud,            |
```

**Comment by justin025** [comment]
The playlist seems to download fine on the latest beta, I have changed the error catcher could you verify:
https://github.com/justin025/onthespot/releases/tag/v1.0.0

If not please send logs located ad %localappdata%/Temp/onthespot

**Comment by 0rkaM** [comment]
Yes, it now works on v1.0.0pre

I noticed many improvements and maybe quirky differences.
Here some notes:

On win10 the '_otsconfig.json_' file still is in the _%appdata%\onthespot_ folder, but the '_credential.json_' file is now in the same folder of the .exe, and not anymore in the _%appdata%\onthespot\sessions_ folder.
I feel they should both be where the app .exe directory is, or both be in the _%appdata%_ subdirs like before.

I noticed there is new toggle options for '_Episodes_', '_Podcasts_', '_Audiobooks_' in the main Search section; I like that.

I personally like the combined '_Advanced_' + "regular" Settings in one tab... but some others could prefer an option to toggle some of them off.
I am fine either way.

The Episode Path now shows as: _**Episodes\{album}\{name}**_ and not anymore as: **_Episodes\{podcast_name}\{episode_name}_**
Is that correct?

The M3U Path is now: **_My_Playlist\{playlist_name} by {playlist_owner}_** and not anymore as: **_My_Playlist\{name} by {owner}_** 
Was the old on an error?

There are not anymore, the '_Play_', '_Save_', '_Queue_' buttons toggles that was in the Advanced Settings before, I turned all of them on once to see what they did, and used only '_Play_' button few times, did not investigate on what '_Save_' and '_Queue_' did... I assume like they could Queue Save and Play the music on the default player or Spotify itself.

Also, no '_Skip Bytes at End_'; are those not needed, not working... problematic?

Since there is no option for '_Max Download Workers_' what is it now? I kind of like to have control over it depending on the account I am using.

The '_Show Download Thumbnails_' does not work independently from '_Show Search Thumbnails_': if the latter is turned on also the former stays on.

There are quite few new meta tags embedding: nice!

One note: I also think that the default audio format for Spotify should be .ogg, so it is straight download without conversion.

P.S.: I am realizing that the reply become longer as I added more notes, and probably could be broken into few bugs and suggestion... do you want me to divide this and create those?

**Comment by justin025** [comment]
0.5. I was wondering about the backstory of your pfp :smile:  

1. Credentials issue is a bug with zeroconf, I will look into it thanks for the heads upsmile
2. I wanted to standardize the pathing for episode and m3u because it seemed every different media type had a different convention, they now all use the same format so that its easier for users
3. I am suprised, you must have been one of the only users beside myself who used the play feature. Save and queue would save to liked songs in spotify or queue the song in spotify. The reason I removed them is that I would like to convert onthespot into a multiservice gui music downloader and it would not make sense to have service specific buttons in the download queue.
4. Skip bytes at end seemed to be unnecessary in my testing, songs downloaded fine without them. The reason that it was added was the logic behind the old downloader, it would put heavy focus on the file length and if it did not align with the metadata it would just fail. The new downloader just continues to download until there are no chunks remaining regardless of length. I figure this system is better.
5. I was wondering about even keeping max download workers because spotify ratelimits accounts after in some cases 50 downloads, would it make any sense to keep additional download workers instead of the 'rotate active accounts' feature? If we did the former your accounts would all rate limit 10/15 minutes in whereas rotate active accounts can run all night. I think advanced users who have 20 spotify premium accounts and want to rip music at lightning speeds will have to look at cli alternatives. I can add download workers back if this is a make or break feature for you.
6. They do work independently but they are not toggled dynamically (yet) meaning that items inside the queue that had thumbnail enabled at time of download will keep thumbnail enabled until cleared whereas new items will not.
7. Most users prefer the mp3 format because it is the most widely supported audio format, for 90% of users they simply want to download music and I am sure I will receive quite a few issues complaining that a weird 'ogg' file was downloaded, 'where is my mp3'. Perhaps a chart in the readme explaining the default file formats or a column in the login table would be better.
8. Nah its ok

**Comment by 0rkaM** [comment]
1. thank you
2. excellent
3. don't worry I don't need 'Play', I just check stuff up.
4. understood and your choice seems reasonable, and if it doesn't break just keep it as you made it. (can always be added later if any)
5. no, I don't want more workers, I don't need lightning speed, I just want them down to minimum, I may even approve for longer wait time, even real-time. I just felt safer knowing how many they were (me = knowledge = control ;))
6. OK, I see.
7. OK, so don't need to change default, I can change my own, make it easy for users.
8. Thank you again.

Cheers!

**Comment by 0rkaM** [comment]
One thing I miss in the 1.0.0pre version is the 'Collection Type' column in the Downloads tab, where I was able to see from which playlist were the files from; that helped me see how many were completed, remaining, failed of each playlist... which is important to me to see how many files I have to retry, or find somewhere else to complete a set.

Also I use long 'Download Delay' and with this version I noticed that, compared to before, the process of just populating the queue take very long as well as the program detecting that a file already exists: before on version 0.71 if a series of files existed, the program would skip all (or most) of them till the next missing file and start the download and then it would start the countdown, now it seems that it start the countdown at each file even if they are existing.

So now, if I set the 'Download Delay' to 60, and let's say 3 files out of 50 would fails, if I have to stop and restart the program and reload the 50 file in the queue using my playlist URL, which I have to do to force the program to also create the M3U file, first it takes quite a bit longer than it used to load all 50 file in the queue, but also instead of skipping rapidly all the existing ones and start with the missing right away so the all process would take about the query and queue time + the 3 (files) x 60sec, so ~3+ minutes, now it will take the longer queue time + 50 x 60sec so 50+ minutes.

**Comment by justin025** [comment]
Download delay was removed from 'Already Exists' items and m3u8 issue was fixed, please verify in the latest release

**Comment by 0rkaM** [comment]
Well, v1.0.0 rc5 populates the queue from the Playlist URL, but it fails to download any of the files in the playlist. So no file downloaded and no M3U file written.

The one before that I think was v1.0.0 rc4 also populates the queue and download all of, or at least most of the files fine; only quirk is that now it creates and M3U file with UTF-8 encoding, but the suffix is .m3u instead of .m3u8... which is minor, but not correct.

There is a problem with the inside of the M3U file with v1.0.0.rc4 where it shows '#EXTINF:-1, xxxxxmetadataxxxx' for each line, instead of numbering progressively from first song '#EXTINF: 1, xxxxxmetadataxxxx' to the last N song '#EXTINF: N, xxxxxmetadataxxxx' where v0.71 was doing that correctly.

I am posting two snippets as example.

This first is from M3U file created by the old v0.71 - the file has the correct UTF-8 encoding and suffix .m3u8 - and inside '**#EXTINF**' shows the right progressive numbering:

```
#EXTM3U
#EXTINF:1, Loneliness - Radio Cut [Tomcraft - Loneliness:2003].fogg
C:\Users\0rKaM\Music\OnTheSpot\Tomcraft\[2003] Loneliness\Loneliness - Radio Cut - Tomcraft - Loneliness.ogg
#EXTINF:2, Insomnia - Radio Edit [Faithless - Stag Do Classics:2024].fogg
C:\Users\0rKaM\Music\OnTheSpot\Faithless\[2024] Stag Do Classics\Insomnia - Radio Edit - Faithless - Stag Do Classics.ogg
#EXTINF:3, Adagio For Strings - Radio Edit [Tiësto - Magikal Journey -The Hits Collection 1998 - 2008:2010].fogg
C:\Users\0rKaM\Music\OnTheSpot\Tiësto\[2010] Magikal Journey -The Hits Collection 1998 - 2008\Adagio For Strings - Radio Edit - Tiësto - Magikal Journey -The Hits Collection 1998 - 2008.ogg
#EXTINF:4, Feel the Beat [Darude - Before the Storm, Special Edition:2001].fogg
C:\Users\0rKaM\Music\OnTheSpot\Darude\[2001] Before the Storm, Special Edition\Feel the Beat - Darude - Before the Storm, Special Edition.ogg
#EXTINF:5, Children [Robert Miles - Children (Dance Vault Mixes):1996].fogg
C:\Users\0rKaM\Music\OnTheSpot\Robert Miles\[1996] Children (Dance Vault Mixes)\Children - Robert Miles - Children (Dance Vault Mixes).ogg
#EXTINF:6, Encore Une Fois - Future Breeze Edit [Sash! - It's My Life:1997].fogg
C:\Users\0rKaM\Music\OnTheSpot\Sash!\[1997] It's My Life\Encore Une Fois - Future Breeze Edit - Sash! - It's My Life.ogg
#EXTINF:7, Castles In The Sky [Ian van Dahl - Vocal Trance Hits - The Anthems:2019].fogg
C:\Users\0rKaM\Music\OnTheSpot\Ian van Dahl\[2019] Vocal Trance Hits - The Anthems\Castles In The Sky - Ian van Dahl - Vocal Trance Hits - The Anthems.ogg
#EXTINF:8, God Is a DJ [Faithless - Forever Faithless - The Greatest Hits:2005].fogg
C:\Users\0rKaM\Music\OnTheSpot\Faithless\[2005] Forever Faithless - The Greatest Hits\God Is a DJ - Faithless - Forever Faithless - The Greatest Hits.ogg
#EXTINF:9, Silence - DJ Tiësto's In Search Of Sunrise Remix [Delerium - Odyssey- The Remix Collection:2007].fogg
C:\Users\0rKaM\Music\OnTheSpot\Delerium\[2007] Odyssey- The Remix Collection\Silence - DJ Tiësto's In Search Of Sunrise Remix - Delerium - Odyssey- The Remix Collection.ogg
#EXTINF:10, As The Rush Comes [Motorcycle - As The Rush Comes (Collected, Pt.1):2018].fogg
C:\Users\0rKaM\Music\OnTheSpot\Motorcycle\[2018] As The Rush Comes (Collected, Pt.1)\As The Rush Comes - Motorcycle - As The Rush Comes (Collected, Pt.1).ogg
```

This second is from M3U file created by the recent v1.0.0rc4 - the file has the not incorrect, but improper suffix .m3u even if it still is UTF-8 encoded - and inside '**#EXTINF**' shows the incorrect fixed '-1' numbering:
```
#EXTM3U
#EXTINF:-1, Kx5; deadmau5; Kaskade; HAYLA - Escape (feat. Hayla)
C:\Users\0rKaM\Music\OnTheSpot\Kx5\[2022] Escape (feat. Hayla)\Escape (feat. Hayla) - Kx5 - Escape (feat. Hayla).ogg
#EXTINF:-1, deadmau5; Kaskade; John Summit - I Remember - John Summit Remix
C:\Users\0rKaM\Music\OnTheSpot\deadmau5\[2023] I Remember (John Summit Remix)\I Remember - John Summit Remix - deadmau5 - I Remember (John Summit Remix).ogg
#EXTINF:-1, Shouse; David Guetta - Live Without Love
C:\Users\0rKaM\Music\OnTheSpot\Shouse\[2023] Live Without Love\Live Without Love - Shouse - Live Without Love.ogg
#EXTINF:-1, Supermode; MEDUZA - Tell Me Why - MEDUZA Remix
C:\Users\0rKaM\Music\OnTheSpot\Supermode\[2022] Tell Me Why (MEDUZA Remix)\Tell Me Why - MEDUZA Remix - Supermode - Tell Me Why (MEDUZA Remix).ogg
#EXTINF:-1, Hypaton; David Guetta; La Bouche - Be My Lover (feat. La Bouche) - 2023 Mix
C:\Users\0rKaM\Music\OnTheSpot\Hypaton\[2023] Be My Lover (feat. La Bouche) [2023 Mix]\Be My Lover (feat. La Bouche) - 2023 Mix - Hypaton - Be My Lover (feat. La Bouche) [2023 Mix].ogg
#EXTINF:-1, GUESSWHO; Lucky Guess; Lena Sue - Secret
C:\Users\0rKaM\Music\OnTheSpot\GUESSWHO\[2024] Secret\Secret - GUESSWHO - Secret.ogg
#EXTINF:-1, John Summit; HAYLA - Where You Are
C:\Users\0rKaM\Music\OnTheSpot\John Summit\[2023] Where You Are\Where You Are - John Summit - Where You Are.ogg
#EXTINF:-1, Jan Blomqvist; Elena Pitoulis - More
C:\Users\0rKaM\Music\OnTheSpot\Jan Blomqvist\[2016] More\More - Jan Blomqvist - More.ogg
#EXTINF:-1, Exit Coda - First Time
C:\Users\0rKaM\Music\OnTheSpot\Exit Coda\[2024] First Time\First Time - Exit Coda - First Time.ogg
#EXTINF:-1, MEDUZA; HAYLA - Another World
C:\Users\0rKaM\Music\OnTheSpot\MEDUZA\[2024] Another World\Another World - MEDUZA - Another World.ogg
```

**Comment by 0rkaM** [comment]
Here is an example of the problem with 1.0.0rc4:
The playlist https://open.spotify.com/playlist/5CMvAWTlDPdZnkleiTHyyo?si=4719490776774536 contains 113 songs, but only 100 were queue.
Also song number 72 'The best Part' said it failed and it was not added to the playlist, but I don't see why, since it seems that even the lyrics were retrieved, and when I clear up all the complete and only that one remained, I then press 'Retry Failed' and it said 'Already Exists'. (??)

In the saved M3U playlist song number 72 'The best Part' is missing, where it should have been between line 143-144 and 145-146.
Here is the Playlist saved by OTS (I had to change the suffix from .m3u to .txt to add it here):
[Progressive House 2024 by Soave.txt](https://github.com/user-attachments/files/17517097/Progressive.House.2024.by.Soave.txt)


and here is the log file:
[onthespot.log](https://github.com/user-attachments/files/17517019/onthespot.log)

So this M3U playlist miss song number 72 in the list even if the song existed/was-downloaded and the thirteen songs past song number 100, where they should all been there in the playlist and the thirteen missing songs should also be added to the queue for download/checking-exist.

**Comment by 0rkaM** [comment]
This is the log of v1.0.0rc5 which fails completely to download the playlist at URL https://open.spotify.com/playlist/5CMvAWTlDPdZnkleiTHyyo?si=4719490776774536 and also only queue up to hundred songs missing the last thirteen:
[onthespot.log](https://github.com/user-attachments/files/17517664/onthespot.log)

**Comment by justin025** [comment]
I put out a warning about this on discord, item pathing has changed {rel_year} changed to {year}

Reset your settings :wink:

**Comment by justin025** [comment]
As for the -1 I read that #EXTINF:{number} is actually supposed to be the duration or length of the song and not the number in a playlist, which is why I changed it to -1 to follow the spec (i can also add the length in milliseconds or minutes). The order of the urls or file path is supposed to be the order. Let me know if this is not correct

**Comment by justin025** [comment]
fixed the playlist queue bug in the latest commit, check rc6

**Comment by justin025** [comment]
This issue has gotten a little long and has multiple different topics/features involved. I'm going to close this issue but please reopen any individual problems in seperate issues, ie one for m3u bugs one for playlist bugs. Thanks for all your help with finding bugs
