### ISSUE TITLE
Antivirus Detected as Threat On Dev Release

### ISSUE THREAD

**Issue by nooobmster69** [justin025/onthespot#34]
### Feature Description

![image](https://github.com/user-attachments/assets/cf4f08c1-e8a6-420a-8ce5-6d3293563996)

### Justification

Antivirus Detected as Threat On Dev Release

**Comment by justin025** [comment]
Just uploaded a new exe now but that probably wont change things, read this https://github.com/justin025/onthespot/issues/10

Try scanning the exe on [virustotal](https://www.virustotal.com/gui/)
