### ISSUE TITLE
How do I download my liked songs?

### ISSUE THREAD

**Issue by h3ndrik** [justin025/onthespot#36]
I'm not sure if that's missing in the documentation, or not implemented... But I can't figure out how to download my Liked Songs playlist.
It seems to have the following URL: https://open.spotify.com/collection/tracks

If I put that into OnTheSpot, it says: `Unable to parse inputted URL.`

**Comment by justin025** [comment]
Open the spotify desktop app, create a new playlist, navigate to liked songs, ctrl-a, ctrl-c, go to new playlist, ctrl-v. Paste new playlist link into onthespot.

at present onthespot does not have the ability to view liked songs but I will definetly add this to my todo list.

**Comment by justin025** [comment]
Fixed in the latest dev build https://github.com/justin025/onthespot/releases/v1.0.0
