### ISSUE TITLE
embed spotify ID in custom attribute

### ISSUE THREAD

**Issue by chalda** [justin025/onthespot#39]
### Feature Description

restore previous feature from OG repo to add spotifyID as a comment or a custom tag

### Justification

ive been meaning to write a script to better match files if they are moved or renamed. This is pretty common if you have any software managing a library such as iTunes or MusicBee

**Comment by justin025** [comment]
Just to clarify in this track for instance: https://open.spotify.com/track/2plbrEY59IikOBgBGLjaoe

 spotifyID would be 2plbrEY59IikOBgBGLjaoe is this correct?

**Comment by justin025** [comment]
Added this in the latest commit
