### ISSUE TITLE
When adding album or artist, if a song is unavailable in that list on Spotify, it will silently stop queuing.

### ISSUE THREAD

**Issue by solunafantasy** [justin025/onthespot#40]
### Feature Description

When adding album or artist, if a song is unavailable in that list on Spotify, it will silently stop queuing, and it will be impossible to queue more lists to download, until you restart the app completely.  It is easy to reproduce the issue if you use the following artist and album example in the screenshots.

### Justification

Its a major issue which is time consuming and confusing to identify.

### Additional Information

<img width="823" alt="ex1" src="https://github.com/user-attachments/assets/5c92904b-ed0b-4235-a2ef-0274d52e0bb2">
<img width="893" alt="ex2" src="https://github.com/user-attachments/assets/9c8984dc-ebbc-4506-b249-82594078d190">

**Comment by justin025** [comment]
This album is not what I'm used to but is quite good thanks for sharing. Fixed in the latest dev release, https://github.com/justin025/onthespot/releases/v1.0.0

**Comment by solunafantasy** [comment]
The issue is still persisting. Adding that album no longer causes it, but If you add the artist, it seems to still do it. The original report isn't the only step causing the bug. There is something else also triggering it.

**Comment by justin025** [comment]
Please send the link and logs if possible, located at %localappdata%/Temp/onthespot

**Comment by solunafantasy** [comment]
I will when I am able to in the next 24-48 hours.

**Comment by justin025** [comment]
sounds good

**Comment by justin025** [comment]
I believe this is no longer the case so I will close this issue, let me know or reopen the issue if you encounter a similar issue in the latest release
