### ISSUE TITLE
Failed to execute script 'pyi_rth_pkgres'

### ISSUE THREAD

**Issue by iescly** [justin025/onthespot#45]
Failed to execute script 'pyi_rth_pkgres' due to unhandled exception: {errno 2} no such file or directory: 'C:\\users\\azziz\\AppData\\Local\\Temp\\MEI84682\\base_library.zip'

Failed to obtain/convert traceback!

**Comment by justin025** [comment]
Is this reproducible on https://github.com/justin025/onthespot/releases/tag/v1.0.0?

**Comment by justin025** [comment]
I believe you reached out on discord and solved your own problem, did you end up fixing this?

**Comment by deadprogramers** [comment]
Yes    it's solved now ❤️
