### ISSUE TITLE
Numbers of maximum tracks you can download per playlist

### ISSUE THREAD

**Issue by homogenic1000** [justin025/onthespot#47]
Hi;

I'm using onthespot because it's the better option to download Spotify playlist but my playlist is about 1200songs and when I start to download my playlist only 376 songs load.

Is there a limit of tracks per playlist?
If yes can I change it on the settings?

Thanks in advance!!

PS: sorry for my bad English it's not my native language

**Comment by justin025** [comment]
There is no limit to the number of items in a playlist, if you feel comfortable you can share your playlist and I can take a look.

Generally when the playlist gets caught at a specific song it means there is something wrong with that song, taking a look at item 377 would be a start.

**Comment by homogenic1000** [comment]
thanks for the response here my playlist link 
https://open.spotify.com/playlist/1EB0knmF5c7IjuUbeBGsW6?si=87e8a060913d41aa

**Comment by ghost** [comment]
Should we wait there?

https://github.com/justin025/onthespot/blob/bcca29c8c502b452897f1b73388cd50ecb582f7f/src/onthespot/api/spotify.py#L275-L297

**Comment by homogenic1000** [comment]
wdym by "Should we wait there?" 
I didn't understand

**Comment by homogenic1000** [comment]
So i've delteted track 377 but now it's stuck at 378. It won't go past 378

**Comment by ghost** [comment]
@homogenic1000 

I found 2 bugs. One is unplayable songs. They have no track, results parse thread crash. Second one is probably because app is simultaneously downloading and collecting metadata to show item on gui, spo servers deny request and QueueWorker thread crashes. 

Can you try the following build and check if it's solved?

https://github.com/ahyora/onthespot/actions/runs/11685386535

**Comment by justin025** [comment]
Should be fixed on the latest commit

**Comment by homogenic1000** [comment]
so now it's stuck at 110 tracks and never had so much failed tracks, the tracks is downloaded at 99% then failed, and onthespot crashed too.

**Comment by homogenic1000** [comment]
so I tried to relaunch it and now track 110 it's not the same it was but now it's loading more tracks really weird, I'll keep updating!

**Comment by homogenic1000** [comment]
okay so now almost 600 tracks have been loaded so it's awesome for now!

**Comment by homogenic1000** [comment]
so onthespot is crashing when I start downloading a playlist so...

**Comment by justin025** [comment]
Could you try resetting your settings and see if that fixes the issue, if not please send logs or a video

**Comment by homogenic1000** [comment]
the video is to big for GitHub and the log are too long for GitHub too so here's a wetransfer with the video
https://we.tl/t-l8MoK96t3Q

**Comment by justin025** [comment]
I'll check the playlist again on macos

**Comment by justin025** [comment]
I'm a little late but I was able to queue and download the entire playlist on both bigsur and ventura using the latest release, if the problem persists feel free to reopen the issue.
