### ISSUE TITLE
Not grabbing all artists, considering duplicate tracks when another artist is involved

### ISSUE THREAD

**Issue by zerog13** [justin025/onthespot#5]
Downloaded Katy Perry - Teenage Dream: The complete confection - https://open.spotify.com/album/5BvgP623rtvlc0HDcpzquz

It considers Track 8- E.T. and Track 17- E.T. the same, but 17 has Kanye West

![image](https://github.com/user-attachments/assets/73aeb83b-4cae-41eb-a240-ab1f8f3ea2ee)

![image](https://github.com/user-attachments/assets/1bcd0cda-ebc6-4d59-a063-aa0baa76c102)

Same with Track 18 which has Missy Elliot, it just marks them as "already exists" and moves on.

This is how I save the files - {artist}\{album} - {rel_year}\{artist} - {album} - {name} - not sure if there is another variable I should put for multiple artists.

**Comment by zerog13** [comment]
It removed the backslashes, here is track path variables.

![image](https://github.com/user-attachments/assets/1da1e6df-99ff-4944-8146-294513b720f3)

**Comment by zerog13** [comment]
I have a workaround by adding {track_number} to the filename, but i don't remember it like this before the fork, but i could be completely wrong.

**Comment by justin025** [comment]
> I have a workaround by adding {track_number} to the filename, but i don't remember it like this before the fork, but i could be completely wrong.

I was just about to write this, im glad you found a solution. I believe it was like this before the fork you possibly just changed your settings.

**Comment by zerog13** [comment]
I thought so, but I found this from March where it showed both artists in the filename, which differentiates the files during download vs the track number.

![image](https://github.com/user-attachments/assets/98957bbf-42ce-47d4-ab98-41be3c49fe0a)

**Comment by justin025** [comment]
Ill set this to the default setting in future releases

**Comment by zerog13** [comment]
your fork is still the best i've used, lots of functionality and super simple.
