### ISSUE TITLE
Issue: Multi-Disc Album Downloads Skip Songs

### ISSUE THREAD

**Issue by hellerphilipp** [justin025/onthespot#54]
### Feature Description

When Downloading Multi-Disc Albums (e.g. Angel Witch – [Angel Witch](https://open.spotify.com/album/4uL3yn9nCDNOr0Dj4ycdqn?si=1tYUfU4gQ16oSNMOVappWg)), it seemingly skips tracks on discs n>1 whose track# already appears on disc#1 as "already exists":

### Justification

This forces one to manually re-queue the songs in questions – would be great if the app could handle these cases!

### Additional Information
I picked the album below as I physically own it, but I assume the same happens for other albums.

<img width="688" alt="image" src="https://github.com/user-attachments/assets/76975efa-7842-4b48-96bf-af02d699072b">

<img width="335" alt="image" src="https://github.com/user-attachments/assets/61511398-fe21-4675-b480-b0d7d0aa5790">

<img width="277" alt="image" src="https://github.com/user-attachments/assets/6daf8ad8-b784-4260-8730-f5a7a2443945">

**Comment by justin025** [comment]
Is this 1.0.1 or 1.0.2, it seems to be fixed in the latest release

**Comment by hellerphilipp** [comment]
That was fast – just noticed I'm on 1.0.1 (didn't get an update notification). 

Will test again to verify, thanks.
