### ISSUE TITLE
In the release page the recent release 1.0.2 shows the wrong names and Checksum.

### ISSUE THREAD

**Issue by 0rkaM** [justin025/onthespot#56]
I just noticed that the recent release v1.0.2 is shown as v1.0.1 and also the wrong checksums are shown.
The actual files are correct (I think), but this may confuse people and also, they cannot match the checksums
![OtS 1 0 2 wrong checksum](https://github.com/user-attachments/assets/291ec79a-f8fa-4a64-99bc-a410810c4da5).

**Comment by justin025** [comment]
Thank you, fixed
