### ISSUE TITLE
Does not work for non-premium accounts

### ISSUE THREAD

**Issue by legaldeejay** [justin025/onthespot#57]
Hello.  I was using this with a non-premium account, but it suddenly stopped working and I just get failed downloads.   Is this supposed to work with non-premium accounts?

**Comment by Lolguy8321** [comment]
sup
yeah it def works
u probably have the rate limiting issue if onthespot downloads songs too fast spotify rate limits ur account
u either
1. increase the download delay 
![image](https://github.com/user-attachments/assets/c0ca4870-f523-492c-8093-5bf0e08e1ac3)
i have mine set to 10 and even with one singular account i got around 70 songs downloaded np
or u can

2. add more accounts

now those two will not eradicate the rate limiting as thats bound to happen at some point but it can def mitigate it from occuring

btw whats ur onthespot version?

**Comment by legaldeejay** [comment]
I am using the Windows version.  Where is the setting to change the rate?

**Comment by legaldeejay** [comment]
Never mind.  I found the setting.  Thanks for your help.

**Comment by legaldeejay** [comment]
Having a new issue.  Downloads work on my Windows 10 desktop, but not on my Windows 11 laptop.   On the laptop, downloads fail instantly no matter what account I use.  Any suggestions?

**Comment by legaldeejay** [comment]
And I fixed that issue too.  I deleted all instances of onthespot then ran it again and it works.  Also, I think there is an issue if using the same account on more than one device.

**Comment by Lolguy8321** [comment]
> And I fixed that issue too. I deleted all instances of onthespot then ran it again and it works. Also, I think there is an issue if using the same account on more than one device.

hm thats weird dont think it should cause anything the dev has to look at that one

**Comment by stevecole90099** [comment]
If you still run into failed downloads try a delay of 25 or 30. It seems to be the sweet spot to download slow enough to not hit the limit.

**Comment by justin025** [comment]
Downloading from the same account on multiple devices will inevitably hit rate limits much faster. When you hit a rate limit you just need to wait 15-30 minutes and try again or try rotating between multiple accounts
