### ISSUE TITLE
when a track is "unavailable", clicking the "clear completed/cancelled items" clears that track rather than leaving it so user knows what is missing

### ISSUE THREAD

**Issue by zerog13** [justin025/onthespot#6]
when a track is "unavailable", clicking the "clear completed/cancelled items" clears that track rather than leaving it so user knows what is missing

**Comment by justin025** [comment]
Should be fixed with the commit below, provide a track url to test.

**Comment by zerog13** [comment]
ok cool. i'll test. haven't had issues with it not getting "unavailable" tracks actually, just a few i found and when i cleared the "finished" tracks, it cleared the few tracks that were unavailable and i couldn't easily tell what i lost lol.

https://open.spotify.com/album/4eYQEkZqw78RC4ia2Txo8l

**Comment by zerog13** [comment]
hey man, i don't work on github much, but i like what you're doing. thanks for not being a dick if i'm doing things the wrong way or in an inefficient manner.

**Comment by justin025** [comment]
> hey man, i don't work on github much, but i like what you're doing. thanks for not being a dick if i'm doing things the wrong way or in an inefficient manner.

There is no such thing as a wrong way, the whole point of github issues is to share problems with the program. Because you opened this issue I was able to push a fix, so thanks. 

The new version should probably be released sometime this weekend.
