### ISSUE TITLE
Add Filetype to m3u 

### ISSUE THREAD

**Issue by LKSPRV** [justin025/onthespot#60]
### Feature Description

Please add the filetype of the downloaded file to the m3u.
Currently (Username removed):

```
#EXTM3U
#EXTINF:262, Danger - 6.24
C:\Users\%username%\Music\OnTheSpot\Tracks\Various Artists\[2016] Furi (Original Game Soundtrack)\2. 6.24
```

Should be:
```
#EXTM3U
#EXTINF:262, Danger - 6.24
C:\Users\%username%\Music\OnTheSpot\Tracks\Various Artists\[2016] Furi (Original Game Soundtrack)\2. 6.24.mp3
```

### Justification

Currently the m3u file (if enabled in the app) creates a link to the File without the filetype.
Programs like VLC cant play the file because it cant find it.
VLC Error (Username removed) :
`filesystem error: cannot open file %Filepath%\xyz (No such file or directory)`

It can be fixed if i manually add the filetype (in my case mp3) for all songs in the m3u8 file

### Additional Information

Thank you very much for all the effort <3

**Comment by justin025** [comment]
This was actually an accident that I forgot to fix, the latest commit fixes the issue you can access it under the actions tab

**Comment by LKSPRV** [comment]
Thank you
