### ISSUE TITLE
V 1.0.2 crashes on MacOS Ventura when starting download from within search results

### ISSUE THREAD

**Issue by twain-28** [justin025/onthespot#62]
Hello there,

I am on my Mac on OSX Ventura, and I have just updated to latest version (1.0.2), by compiling and building the binary myself from source, since the app inside the pre-compiled DMG was not recognized as valid by my system (search me why).
The code builds fine, I copy the program in the Applications, run it, it correctly logs on my Spotify account. 
So I go to the search tab and look for an album. I wait for the search results to load, than I choose one (any random one) from the list, and the usual "playlist is being added" message pops out.
Immediately after that, the software crashes, without any warning or message. I can provide the base MacOS traceback, but AFAIK that might not be so useful. Just give the word, if you want it.
IMHO, this issue might be related to the "download" button, that was not working in previous release; mabe the fix broke it altogether. 
I tried doing the search via my browser (so obtaining a public playlist), then pasting the URL in the search bar on OnTheSpot and hitting "enter"; that way, the parser works fine, no crash, dowload works perfectly.

**Comment by justin025** [comment]
Tried out the latest release on macos ventura and hopefully it works. In the event you are still experiencing this error feel free to reopen the issue, you can try running the build script yourself aswell all that is necessary is python and git (both included in xcode tools)
