### ISSUE TITLE
Adding a formatting field for the EXTINF Song Naming.

### ISSUE THREAD

**Issue by 0rkaM** [justin025/onthespot#66]
### Feature Description

It would be nice to have a field to customize the name formatting, arbitrary and separator characters that is placed in the EXTINF field of the playlist, like we can do in the path naming.

So that those are visualized in the respective player as the user better see fit, separated from the actual file naming and path.

I would leave to the default EXTINF formatting we have right now for everyone, but adding the capability to customize it for who wants and/or need it, so that not only we can make nicer looking, or more informative song titles, but also on certain player that cannot, or won't accept to show certain characters, like punctuation, separations, or whatever else, it would not cause problems, without having to change the actual file naming and path.

### Justification

Some player does not accept, or render certain characters well, with some just showing ugly characters while other straight-out freeze/ crash.

Also, it gives the options for embellished, longer more informative titles, etc.

**Comment by justin025** [comment]
The m3u function checks if the line already exists in the m3u file and then if it does not adds the line. Currently I have 
{playlist_number}. {artist} - {title} = #EXTINF:254, 1. Artist - Title

What formatting do you use and I will set that as the default with an option to change

**Comment by justin025** [comment]
Slipped this into 1.0.3, let me know your thoughts
