### ISSUE TITLE
Some failed downloads and some downloaded but shown as failed... Plus not working playlist because of file path mismatch.

### ISSUE THREAD

**Issue by 0rkaM** [justin025/onthespot#69]
I encountered few problems downloading this playlist: https://open.spotify.com/playlist/5SXnuXNoLcBUc11VIOi5r0?si=9564e6bf46ad44f5

**### Problem 1:**
Song number 6 'Alone in the Town' by Akira Yamaoka even if it is available, it fails to download and also it is not put into the playlist, but the relative folder for the artist 'Akira Yamaoka' and album folder '[2001] SILENT HILL2 （Original Soundtrack）' are created... why did it stop there and not continue with actual audio file download?
I am not sure if this is relevant, but please note how the parenthesis in the folder name **are not regular parenthesis** as in
U+0029 : RIGHT PARENTHESIS
, but they are
U+FF09 : FULLWIDTH RIGHT PARENTHESIS.
Maybe there are other special characters, and the problem is not in downloading, but in creating the file name with those characters!?
But if they cause a problem, they be caught by the 'Illegal Character Replacement' option, right?
Could this be part of, or related to the problem for failed downloads and loops like in #43?
(here is the link to the song by itself:
https://open.spotify.com/track/49AOg6cq6XRdYzP1JOPXm0?si=e45777be33214b2d)

**### Problem 2:**
Song number 13 'Building Steam with a Grain of Salt' will also show as failed in the queue, but this time it will be downloaded into the right path, but in the playlist the file path will be save as:
```
#EXTINF:399, DJ Shadow - Building Steam With A Grain Of Salt
C:\Users\user\Music\OnTheSpot\DJ Shadow\[1996] Endtroducing.....\Building Steam With A Grain Of Salt - DJ Shadow - Endtroducing......ogg
```
Note the 5 extra dots/periods '.....' on both the end of the directory and at the end of the audio name before the regular prefix (.ogg in my case)

That render the file not been found by the player, since that directory and that file with the extra '.....' do not exist.

Note that the album name in Spotify does have the extra '.....', but it is not saved like that in the actual directory and file names, but only in the playlist path.
( here is the link of the song by itself:
https://open.spotify.com/track/4cucslsiEgezV2o900Ykg3?si=4b3b247710fa400e)

**Comment by justin025** [comment]
Problem 2 is windows doesnt allow path names to end in a '.', ill look at both now and get back to you.

**Comment by justin025** [comment]
Do these problems still occur on 1.0.3 it looks like the metadata you listed was from 1.0.2 (as I opted to include {playlist_number} to avoid duplicates) but perhaps I'm wrong.

The item path should be sanitized and remove following periods '.' if you are on windows. The whole playlist seemingly downloaded fine, also try making a folder with '（' and '）' in the name.

**Comment by 0rkaM** [comment]
I think it was 1.0.2, but not 100% sure since I also removed the {playlist_number} from the 'M3U Path' settings, in my case it was redundant: when the playlist is loaded in my players, songs are visualized as a progressive number and then the playlist EXTINF data, so if I left that in it would look like this:

```
1. 1. DJ Shadow - Building Steam With A Grain Of Salt
2. 2. some_other_song.
3. 3. etc.

```

By 'The item path should be sanitized and remove following periods' you mean the program should sanitize it as per last build, or I should sanitize it by defining '.' (the period char) as illegal char and sub it for something else?

And are you suggesting I'll add the parenthesis characters to enclose Directories names in the 'Track Path' pattern of the app settings? All the Directories names... Artist... Album... etc.?

P.S.: one unrelated question about two setting options: what is the purpose, or the difference between the 'Playlist Path' and the 'M3U Path'?

**Comment by justin025** [comment]
Windows does not allow you to have a file name end in . if you would like to include album name and such in brackets that is a stylistic choice up to you the app should sanitize either way as seen below in the following code:

https://github.com/justin025/onthespot/blob/d4e98cb111c8c8a7769ab79411dd44e97d899685/src/onthespot/utils.py#L52-L64

As you can see at the bottom while the file name ends in '.' (say test.) then remove the last character and try again. Not entirely sure why your m3u has a ... added maybe it was an old version? I couldn't reproduce on 1.0.3 windows 11, default settings.

>P.S.: one unrelated question about two setting options: what is the purpose, or the difference between the 'Playlist Path' and the 'M3U Path'?

Some users liked having their playlists songs in a separate folder to say their general collection. If 'Use Custom Playlist Path' is checked then mp3s (or your choice of format) that are in a playlists will be saved to a different folder (specified by playlist path), M3U path on the other hand is the path where the m3u files will be saved if 'create m3u file for playlists' is checked. There is a bit of documentation [here](https://github.com/justin025/onthespot/blob/main/docs/usage.md) but I would like to reorganize things to be more clear at some point. Hope this clears things up.
