### ISSUE TITLE
Different character to translate the MetaData separator to one for the file path, names, and playlist.

### ISSUE THREAD

**Issue by 0rkaM** [justin025/onthespot#70]
### Feature Description

Would be nice to have two different selectable options for the Character to be used as separator for the MetaData, to the file path and to the playlist song name (in the EXTINF).

### Justification

This is not only for image and style purposes, but separator character that can be OK for generic visualization of MetaData separation into some software are sometime not adequate and can create parser problem when used for the file name and path in certain OSes and applications and the same character is sometime not acceptable, or working for the playlist naming to be shown in dedicated players displays.

### Additional Information

> The real separator between multi-value fields is a binary 0. For example, MP3tag uses the \\ to show (only show) that there are several fields of the same type, but in the tag, they are still separated by the binary 0.
> Other characters as separators are down to the respective player, E.g. the "; " is used by > WMP but not by iTunes, so in WMP "Peter Gabriel; Kate Bush" would lead to separate
> entries in the artists list whereas iTunes would still show "Peter Gabriel; Kate Bush".
> The same applies to other fields.
> Some players can cope with real multi-value fields, others can't and show only the first entry they come across...
> and some other players just skip the song, or freezes all together.

**Comment by justin025** [comment]
what is the default m3u EXTINF seperator

**Comment by justin025** [comment]
slipped this into 1.0.3 let me know your thoughts
