### ISSUE TITLE
Different version of OnTheSpot create playlist with different encoding: Windows-1252 (subset of ANSI), ANSI, UTF-8 and UTF-8BOM which leave some song unloadable

### ISSUE THREAD

**Issue by 0rkaM** [justin025/onthespot#71]
I noticed that when I loaded a playlist created by OtS, some song would not play and at first, I thought they were missing from the respective folders, but they were not. Then I noticed that some songs from the same playlist would play on some players, but not on other.

After some investigation I saw that the song that would not play where the one with some special characters in the title and/or path; I then find out that was not the actual special character alone, but in concomitance with how the playlist files were encoded: some were encoded in ANSI, some in UTF-8, some UTF-8 with BOM and other in Windows-1252 which is the old Microsoft ANSI subset.
Most players today can play ANSI including Windows-1252 without special characters, and UTF-8 (and UTF-8BOM) with special characters.

Since the OtS program get the names of the songs from Spotify and some contain special characters in the various MetaData, it happened that in the various version iteration of the program, playlist files were created with all kinds of variations of ANSI/Window-1253 with special characters, and some UTF-8 and UTF-BOM with special characters, and the problem is that quite few players reject path and song name with special characters when it is not in UTF-8 encoding, like for example even the latest Foobar2000.

I am going to fix the encoding of the problematic file by using an editor like Notepad4, Notepad++, etc to modify the encoding and resave them, but I would suggest for future version of OtS to only use UTF-8 encoding to create playlist text files, to not incur into the above problem.

**Comment by justin025** [comment]
hardcoded utf8 in 1.0.3 hopefully this fixes it
