### ISSUE TITLE
Is this file save? It´s detected as malware... 

### ISSUE THREAD

**Issue by andrefromsbg** [justin025/onthespot#72]
### Feature Description

I use virustotal always to check files from unknown developers. Some virusscanners detect malware in this file. What´s going on?
![Screenshot 2024-11-23 120501](https://github.com/user-attachments/assets/3526f2a0-bd4a-4764-8334-842fc37c349f)

### Justification

malware is not good

**Comment by justin025** [comment]
https://github.com/justin025/onthespot/issues/10

The builds are auto built by github, if you'd like you can build the app from source or check the source code.
