### ISSUE TITLE
Separated settings for path specification for Albums / Singles and EPs.

### ISSUE THREAD

**Issue by brydlstepan** [justin025/onthespot#74]
### Feature Description

Separated settings for path specification for Albums / Singles and EPs. simillar to the current Tracks and Episode.

### Justification

There are a lot of tools that have specific file structure needs. It would be great if we could specify the saving paths and names based on the downloaded media type.

**Comment by justin025** [comment]
Maybe we can do something different say add a new tag called {album_type} which would then output Single, Album, Collab etc.

Then you could add the format {album_type}/{track_number}. {name} = Single/1. Track Name

Let me know if this works.

**Comment by brydlstepan** [comment]
Yes that should work as well. <3

**Comment by justin025** [comment]
under the actions tab in github the latest commit should have the feature you're looking for. Let me know if it works

**Comment by brydlstepan** [comment]
Works well! Thank you
