### ISSUE TITLE
Add option to add downloads to a queue before downloading 

### ISSUE THREAD

**Issue by legaldeejay** [justin025/onthespot#76]
### Feature Description

Add option to add downloads to a queue before downloading 

### Justification

So you don't have to download right away

**Comment by justin025** [comment]
you can add urls to a text file and paste its path in the search bar, the app will parse the text file and queue the songs. In the latest commit I added a copy button beside download so you can copy, paste into a file and repeat. When you are done you can search the file and it will download all your songs listed, hope this works for you.

**Comment by legaldeejay** [comment]
OK thanks.
