### ISSUE TITLE
Add option to select which tracks to download from albums and playlists

### ISSUE THREAD

**Issue by legaldeejay** [justin025/onthespot#78]
### Feature Description

Add option to select which tracks to download from albums and playlists

### Justification

You would not have to open Spotify to see what is in an album or playlist and you would not have to download entire albums or playlists, but only the parts you want

**Comment by justin025** [comment]
I've added a 'copy url' button to search so it is as simple as pasting that in your browser for playlists and albums, I may consider having something inside the app at some point in the future but as of right now I will be closing this.
