### ISSUE TITLE
OnTheSpot not appearing under "devices" in the Spotify App

### ISSUE THREAD

**Issue by fabiolalacalva** [justin025/onthespot#80]
I've found this amazing tool and decided to try it out for myself. I've tried to add my Spotify account for download and it prompted me to add OnTheSpot under Devices in the Spotify web app. Unfortunately, there is no device or service associated with the app in Spotify. I've tried reinstalling Spotify, opening, closing, reloading, etc. (basic stuff you know...) I've also read instructions and all information available but nothing seems to work. I will upload some screenshots if it helps. Thanks in advance and sorry for the inconvenience. 
![Screenshot (69)](https://github.com/user-attachments/assets/cd0e3acb-9a89-4bbe-b1f5-bb9dd4865ed5)
![Screenshot (68)](https://github.com/user-attachments/assets/1a6997a8-bf42-48cc-b4af-42d1a894aeb6)

**Comment by justin025** [comment]
Did you allow both spotify and onthespot in the windows firewall popup? What windows version is this and does the app logins work on a different computer (if you have one)

**Comment by Moon-Drop93** [comment]
Same issue with Linux, it wont properly connect and if you attempt anything, all youll get is failed downloads

**Comment by justin025** [comment]
Set download delay to 35 and it will not fail, please check the pinned issues

**Comment by Moon-Drop93** [comment]
Sorry, but that didn't fix anything. I didn't have this issue on Windows; it would connect and go green, showing that it did connect, but on Linux it stays white. At least for me, it stays on connecting on Spotify but says its connected on the app, but all the downloads show up as failed with an "mp3 file," but it can't be played.

**Comment by justin025** [comment]
yes that is how the app connects, please provide logs %localappdata/Temp/onthespot or .cache/onthespot

**Comment by fabiolalacalva** [comment]
I've downloaded the application on my laptop and it works perfectly... I've allowed all connections through the firewall, but it still doesn't work on my main PC though. I'm running Windows 10 (build 19042). Do you know of anything else that could be interfering with the app? Thanks a lot for your support <3

**Comment by justin025** [comment]
At that point just copy the config file to your pc at %appdata%/onthespot/config.json

**Comment by fabiolalacalva** [comment]
That worked! Thank you so much for your help and keep up the amazing work!
