### ISSUE TITLE
could not connect to Spotify

### ISSUE THREAD

**Issue by Gene22** [justin025/onthespot#84]
I have just built the latest version from the GIT for Linux (1.0.4).
I am not able to connect to Spotify.
When I press “add spotify account”, the application just waits and nothing happens.
My Spotify client is 1.2.52.442-1

**Comment by justin025** [comment]
did you click 'OnTheSpot' under devices in the spotify app?

**Comment by Gene22** [comment]
> did you click 'OnTheSpot' under devices in the spotify app?

Yes I did - last Saturday with the old versions (Spotify and onthespot) it works well

**Comment by justin025** [comment]
I'm glad it worked
