### ISSUE TITLE
Add auto retry downloading option

### ISSUE THREAD

**Issue by lostmaintenance666** [justin025/onthespot#87]
### Feature Description

I’d like to suggest a feature that could improve the reliability of the downloading process: automatic retry on failure.

### Justification

1. Enhance the tool’s reliability, especially for larger downloads where occasional errors or timeouts are expected.
2. Save users time and frustration by reducing the need for manual intervention when errors occur.

**Comment by justin025** [comment]
For spotify you can try setting the download delay to 35 seconds to prevent failed downloads. Closing this issue in favour of https://github.com/justin025/onthespot/issues/75
