### ISSUE TITLE
Where does Onthespot save the accounts/configfile under macOS?

### ISSUE THREAD

**Issue by WolfgangDpunkt** [justin025/onthespot#89]
The app works fine for me, but then I added the same Spotify account several times, so i had the same account in the list three times, since then the app freezes as soon as it starts. So I can't delete the accounts via the GUI.

After deleting the app and all files that contain the app name in the file name, the accounts are still there again after a reinstallation.

Thanks for your help!

<img width="676" alt="grafik" src="https://github.com/user-attachments/assets/493535d5-e75b-4515-b60b-1889537d7f9c" />

**Comment by justin025** [comment]
Accounts are saved to ~/.config/onthespot/otsconfig.json

To manually reset your settings run the following command:
rm ~/.config/onthespot/otsconfig.json

**Comment by WolfgangDpunkt** [comment]
Thank you, that helped immediately.
